server: 
  port: 8085
spring: 
  application: 
    name: movie-service
  zipkin:
    enabled: true    
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: "jdbc:mysql://localhost:3306/movies?createDatabaseIfNotExist=true"
    username: root
  jpa: 
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate: 
      ddl-auto: update
  session: 
    jdbc: 
      initialize-schema: always
    store-type: jdbc
    timeout: 
      seconds: 10000

eureka:
  server:
    peer-node-read-timeout-ms: 25000
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka           