spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
  management:
    tracing:
      sampling:
        probablity: 1
  cloud:
    gateway:
      routes:
        - id: theater-service
          uri: lb://theater-service
          predicates:
            - Path=/theaters/**
          filters:
            - TokenRelay
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/demo
        registration:
          keycloak:
            client-id: api-gateway
            client-secret: voIdnvHLqSx5tnW37McFSDIiTe0oeFrI
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/demo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8082
